"""Create trained-vs-untrained soil-moisture comparison maps.

The "untrained" map is the shipped model6 prediction already generated by
``run_validation.py``. The "trained" map is a local residual-calibrated variant:
fit a ridge residual corrector from the dense point/date observations and the
actual model6 inputs, then apply that correction to every pixel.

This is not full OzNet+local model retraining. It is a local calibration surface
on top of model6, intended for visualising how dense local observations change
the predicted soil-moisture field.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import date
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DEFAULT_MODEL6_DENSE_DIR = Path(
    "/Volumes/Dmitry_work/borevitz_projects/model6_dense_validation_spiking"
)
DEFAULT_VALIDATION_DIR = Path(
    "/Volumes/Dmitry_work/borevitz_projects/Data/soilmoisture_points_validation"
)
NODATA = -9999.0


def bbox_from_predictions(predictions: pd.DataFrame, padding_deg: float = 0.002):
    return (
        float(predictions["lon"].min() - padding_deg),
        float(predictions["lat"].min() - padding_deg),
        float(predictions["lon"].max() + padding_deg),
        float(predictions["lat"].max() + padding_deg),
    )


def query_stub(bbox, start_day: str, end_day: str) -> str:
    b = "_".join(f"{v:.3f}" for v in bbox)
    return f"smcompare_{b}_{start_day}_{end_day}".replace(".", "p").replace("-", "m")


def ensure_dirs(out_dir: Path, method_label: str) -> dict[str, Path]:
    paths = {
        "root": out_dir,
        "untrained": out_dir / "untrained_model6",
        "trained": out_dir / f"trained_{method_label}",
        "correction": out_dir / f"{method_label}_correction",
        "multiband": out_dir / f"multiband_{method_label}",
        "figures": out_dir / f"figures_{method_label}",
    }
    for path in paths.values():
        path.mkdir(parents=True, exist_ok=True)
    return paths


def fit_residual_corrector(feature_rows: pd.DataFrame, features: list[str], method: str, knn_neighbors: int):
    from sklearn.impute import SimpleImputer
    from sklearn.linear_model import Ridge
    from sklearn.neighbors import KNeighborsRegressor
    from sklearn.pipeline import make_pipeline
    from sklearn.preprocessing import StandardScaler

    model_features = features + ["pred_sm_pct"]
    train = feature_rows.dropna(subset=["residual_obs_minus_pred"]).copy()
    X = train[model_features].replace([np.inf, -np.inf], np.nan)
    y = train["residual_obs_minus_pred"].to_numpy(dtype=float)
    if method == "ridge":
        estimator = Ridge(alpha=1.0)
    elif method == "knn":
        estimator = KNeighborsRegressor(
            n_neighbors=max(1, min(int(knn_neighbors), len(train))),
            weights="uniform",
        )
    else:
        raise ValueError(f"unknown method: {method}")

    corrector = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(), estimator)
    corrector.fit(X, y)
    return corrector, model_features


def metrics(y_true, y_pred) -> dict:
    from emt.evaluation import metrics as _metrics

    return _metrics(y_true, y_pred)


def point_trained_predictions(
    feature_rows: pd.DataFrame,
    corrector,
    model_features: list[str],
    clip_min: float | None,
    clip_max: float | None,
):
    out = feature_rows.copy()
    X = out[model_features].replace([np.inf, -np.inf], np.nan)
    out["local_correction_sm_pct"] = corrector.predict(X)
    raw = out["pred_sm_pct"] + out["local_correction_sm_pct"]
    out["trained_sm_pct_raw"] = raw
    out["trained_sm_pct"] = raw.clip(lower=clip_min, upper=clip_max)
    out["local_correction_sm_pct"] = out["trained_sm_pct"] - out["pred_sm_pct"]
    return out


def write_point_metrics(point_predictions: pd.DataFrame, out_dir: Path) -> dict:
    before = metrics(point_predictions["obs_sm_pct"], point_predictions["pred_sm_pct"])
    after = metrics(point_predictions["obs_sm_pct"], point_predictions["trained_sm_pct"])
    out = {
        "untrained_model6": before,
        "trained_local_residual_in_sample": after,
        "delta": {
            "nse": after["nse"] - before["nse"],
            "rmse": after["rmse"] - before["rmse"],
            "ubrmse": after["ubrmse"] - before["ubrmse"],
            "bias": after["bias"] - before["bias"],
            "abs_bias": abs(after["bias"]) - abs(before["bias"]),
            "r": after["r"] - before["r"],
        },
    }
    with (out_dir / "point_metrics_trained_vs_untrained.json").open("w") as f:
        json.dump(out, f, indent=2)
    point_predictions.to_csv(out_dir / "point_predictions_trained_vs_untrained.csv", index=False)
    return out


def _write_single_band(path: Path, array: np.ndarray, profile: dict, description: str) -> None:
    prof = profile.copy()
    prof.update(driver="GTiff", count=1, dtype="float32", nodata=NODATA, compress="deflate", predictor=3)
    with _rasterio().open(path, "w", **prof) as dst:
        dst.write(np.where(np.isfinite(array), array, NODATA).astype("float32"), 1)
        dst.set_band_description(1, description)


def _write_multiband(path: Path, arrays: list[np.ndarray], profile: dict, descriptions: list[str]) -> None:
    prof = profile.copy()
    prof.update(
        driver="GTiff",
        count=len(arrays),
        dtype="float32",
        nodata=NODATA,
        compress="deflate",
        predictor=3,
    )
    with _rasterio().open(path, "w", **prof) as dst:
        for idx, (array, description) in enumerate(zip(arrays, descriptions), 1):
            dst.write(np.where(np.isfinite(array), array, NODATA).astype("float32"), idx)
            dst.set_band_description(idx, description)


def _rasterio():
    import rasterio

    return rasterio


def _open_template(path: Path):
    import rioxarray  # noqa: F401

    return rioxarray.open_rasterio(path, masked=True).squeeze("band", drop=True).load()


def _align_to_template(da, template):
    from rasterio.enums import Resampling

    if da.rio.crs is None:
        da = da.rio.write_crs(4326)
    return da.rio.reproject_match(template, resampling=Resampling.nearest)


def build_static_layers(q, template):
    from emt.covariates import TERRAIN_VARS, terrain_covariates
    from emt.slga import SOIL_VARS, soil_covariates

    print("loading terrain inputs ...", flush=True)
    terr = terrain_covariates(q)
    layers = {}
    for var in TERRAIN_VARS:
        layers[var] = _align_to_template(terr[var], template)

    print("loading SLGA soil inputs ...", flush=True)
    soil = soil_covariates(q)
    for var in SOIL_VARS:
        layers[var] = _align_to_template(soil[var], template)
    return layers


def build_dynamic_layers(q, dates: list[str], bbox, template):
    from emt.antecedent import antecedent_day_layers, antecedent_grid
    from emt.smips import smips_cube

    print("fetching SMIPS cube for comparison maps ...", flush=True)
    smips_start = (pd.Timestamp(dates[0]) - pd.Timedelta(days=365)).date()
    smips = smips_cube(smips_start, pd.Timestamp(dates[-1]).date(), bbox, var="totalbucket").sortby("time")

    print("loading antecedent SILO grid for comparison maps ...", flush=True)
    ante = antecedent_grid(q, pd.Timestamp(dates[0]).date(), pd.Timestamp(dates[-1]).date())

    out = {}
    for i, day in enumerate(dates, 1):
        print(f"  dynamic layers {i}/{len(dates)}: {day}", flush=True)
        ts = pd.Timestamp(day)
        upto = smips.sel(time=slice(None, ts))
        today = upto.isel(time=-1).rio.write_crs(4326)
        layers = {
            "smips_totalbucket": today,
            "smips_7d": upto.isel(time=slice(-7, None)).mean("time").rio.write_crs(4326),
            "smips_30d": upto.isel(time=slice(-30, None)).mean("time").rio.write_crs(4326),
            "smips_365d": upto.isel(time=slice(-365, None)).mean("time").rio.write_crs(4326),
        }
        layers["smips_anom"] = layers["smips_totalbucket"] - layers["smips_365d"]
        for name, da in antecedent_day_layers(ante, ts.date()).items():
            layers[name] = da.rio.write_crs(4326) if da.rio.crs is None else da

        doy = ts.dayofyear
        layers["doy_sin"] = float(np.sin(2 * np.pi * doy / 365.25))
        layers["doy_cos"] = float(np.cos(2 * np.pi * doy / 365.25))
        out[day] = {
            name: (_align_to_template(value, template) if hasattr(value, "rio") else value)
            for name, value in layers.items()
        }
    return out


def grid_dataframe(features: list[str], static_layers: dict, dynamic_layers: dict, untrained: np.ndarray):
    cols = []
    for feature in features:
        value = dynamic_layers.get(feature, static_layers.get(feature))
        if value is None:
            raise KeyError(f"no grid layer for feature {feature}")
        if hasattr(value, "values"):
            cols.append(np.asarray(value.values).ravel())
        else:
            cols.append(np.full(untrained.size, float(value)))
    cols.append(untrained.ravel())
    return pd.DataFrame(np.column_stack(cols), columns=features + ["pred_sm_pct"])


def make_figure(day: str, untrained: np.ndarray, trained: np.ndarray, correction: np.ndarray, path: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    combined = np.concatenate([untrained[np.isfinite(untrained)], trained[np.isfinite(trained)]])
    vmin, vmax = np.nanpercentile(combined, [2, 98]) if combined.size else (0, 1)
    lim = np.nanpercentile(np.abs(correction[np.isfinite(correction)]), 98) if np.isfinite(correction).any() else 1
    lim = max(float(lim), 0.5)

    fig, axes = plt.subplots(1, 3, figsize=(13, 4), constrained_layout=True)
    specs = [
        ("Untrained model6", untrained, "YlGnBu", vmin, vmax, "soil moisture (%)"),
        ("Locally trained/calibrated", trained, "YlGnBu", vmin, vmax, "soil moisture (%)"),
        ("Local correction", correction, "coolwarm", -lim, lim, "trained - untrained (%)"),
    ]
    for ax, (title, arr, cmap, lo, hi, label) in zip(axes, specs):
        im = ax.imshow(arr, cmap=cmap, vmin=lo, vmax=hi)
        ax.set_title(title)
        ax.set_xticks([])
        ax.set_yticks([])
        fig.colorbar(im, ax=ax, shrink=0.8, label=label)
    fig.suptitle(f"Soil moisture comparison — {day}", y=1.02)
    fig.savefig(path, dpi=160, bbox_inches="tight")
    plt.close(fig)


def method_label(args: argparse.Namespace) -> str:
    if args.method == "knn":
        return f"local_residual_knn{int(args.knn_neighbors)}"
    return "local_residual_ridge"


def generate_maps(args: argparse.Namespace) -> None:
    from PaddockTS.query import Query
    from emt.model6 import model as model6

    out_dir = args.model6_dense_dir / "SM_comparison"
    label = method_label(args)
    paths = ensure_dirs(out_dir, label)
    feature_rows = pd.read_csv(
        args.model6_dense_dir / "stage1_dense_unseen_validation" / "point_date_model_inputs.csv"
    )
    dates = sorted(feature_rows["date"].unique())
    bbox = bbox_from_predictions(feature_rows)

    corrector, model_features = fit_residual_corrector(
        feature_rows,
        list(model6.FEATURES),
        method=args.method,
        knn_neighbors=args.knn_neighbors,
    )
    joblib.dump(corrector, out_dir / f"{label}_corrector.joblib")
    point_pred = point_trained_predictions(
        feature_rows,
        corrector,
        model_features,
        clip_min=args.clip_min,
        clip_max=args.clip_max,
    )
    point_metrics = write_point_metrics(point_pred, out_dir)

    first_tif = args.validation_dir / "tifs" / f"soil_moisture_{dates[0]}.tif"
    template = _open_template(first_tif)
    q = Query(
        bbox=list(bbox),
        start=pd.Timestamp(dates[0]).date(),
        end=pd.Timestamp(dates[-1]).date(),
        stub=query_stub(bbox, dates[0], dates[-1]),
    )
    static_layers = build_static_layers(q, template)
    dynamic_by_day = build_dynamic_layers(q, dates, bbox, template)

    raster_rows = []
    for i, day in enumerate(dates, 1):
        print(f"writing comparison maps {i}/{len(dates)}: {day}", flush=True)
        src_tif = args.validation_dir / "tifs" / f"soil_moisture_{day}.tif"
        with _rasterio().open(src_tif) as src:
            profile = src.profile.copy()
            untrained = src.read(1).astype("float32")
            untrained = np.where(untrained == src.nodata, np.nan, untrained) if src.nodata is not None else untrained

        X = grid_dataframe(list(model6.FEATURES), static_layers, dynamic_by_day[day], untrained)
        valid = np.isfinite(untrained.ravel()) & np.isfinite(X.replace([np.inf, -np.inf], np.nan)).all(axis=1).to_numpy()
        correction = np.full(untrained.size, np.nan, dtype="float32")
        if valid.any():
            correction[valid] = corrector.predict(X.loc[valid, model_features]).astype("float32")
        correction = correction.reshape(untrained.shape)
        trained_raw = untrained + correction
        trained = np.clip(trained_raw, args.clip_min, args.clip_max)
        correction = trained - untrained

        # Keep an exact copy in the comparison folder and also write a standard
        # nodata-tagged version for easier GIS use.
        shutil.copy2(src_tif, paths["untrained"] / f"untrained_model6_{day}.tif")
        _write_single_band(paths["trained"] / f"trained_{label}_{day}.tif", trained, profile, "trained_local_sm_pct")
        _write_single_band(paths["correction"] / f"{label}_correction_{day}.tif", correction, profile, "trained_minus_untrained_sm_pct")
        _write_multiband(
            paths["multiband"] / f"SM_comparison_{label}_{day}.tif",
            [untrained, trained, correction],
            profile,
            ["untrained_model6_sm_pct", f"trained_{label}_sm_pct", "trained_minus_untrained_sm_pct"],
        )
        make_figure(day, untrained, trained, correction, paths["figures"] / f"SM_comparison_{label}_{day}.png")

        raster_rows.append(
            {
                "date": day,
                "untrained_mean": float(np.nanmean(untrained)),
                "trained_mean": float(np.nanmean(trained)),
                "correction_mean": float(np.nanmean(correction)),
                "correction_min": float(np.nanmin(correction)),
                "correction_max": float(np.nanmax(correction)),
                "valid_pixels": int(np.isfinite(trained).sum()),
            }
        )

    pd.DataFrame(raster_rows).to_csv(out_dir / "raster_summary.csv", index=False)
    write_report(out_dir, point_metrics, pd.DataFrame(raster_rows), dates, bbox, args, label)


def fmt(value, digits: int = 3) -> str:
    return "NA" if value is None or not np.isfinite(float(value)) else f"{float(value):.{digits}f}"


def write_report(
    out_dir: Path,
    point_metrics: dict,
    raster_summary: pd.DataFrame,
    dates: list[str],
    bbox,
    args: argparse.Namespace,
    label: str,
) -> None:
    before = point_metrics["untrained_model6"]
    after = point_metrics["trained_local_residual_in_sample"]
    delta = point_metrics["delta"]
    report = f"""# Soil-moisture trained vs untrained map comparison

Output folder: `{out_dir}`

Dates: {", ".join(dates)}

BBox: `{bbox[0]:.6f} {bbox[1]:.6f} {bbox[2]:.6f} {bbox[3]:.6f}` (`W S E N`, EPSG:4326)

## Definition

- **Untrained**: the shipped model6 prediction maps from the independent validation run.
- **Trained**: a local residual-calibrated map. A `{args.method}` residual
  corrector was fitted using all dense point/date observations and the actual
  model6 input features, then applied to every pixel.

This is a local calibration surface on top of model6, not full OzNet+local model
retraining.

Clip range applied to trained predictions: `{args.clip_min}` to `{args.clip_max}`.

## Point-level fit used for the local correction

| metric | untrained model6 | trained `{label}` | delta |
|---|---:|---:|---:|
| NSE / R² | {fmt(before["nse"])} | {fmt(after["nse"])} | {fmt(delta["nse"])} |
| Pearson r | {fmt(before["r"])} | {fmt(after["r"])} | {fmt(delta["r"])} |
| RMSE | {fmt(before["rmse"])} | {fmt(after["rmse"])} | {fmt(delta["rmse"])} |
| ubRMSE | {fmt(before["ubrmse"])} | {fmt(after["ubrmse"])} | {fmt(delta["ubrmse"])} |
| bias | {fmt(before["bias"])} | {fmt(after["bias"])} | {fmt(delta["bias"])} |

Because the correction is fitted to all local point observations, these point
metrics are in-sample and should be read as the strength of local calibration,
not independent validation.

## Outputs

- `untrained_model6/` — copied original model6 GeoTIFFs.
- `trained_{label}/` — locally trained/calibrated soil-moisture GeoTIFFs.
- `{label}_correction/` — correction surfaces (`trained - untrained`).
- `multiband_{label}/` — one three-band GeoTIFF per date: untrained, trained, correction.
- `figures_{label}/` — quick-look PNG triptychs for each date.
- `point_predictions_trained_vs_untrained.csv` — point-level before/after predictions.
- `raster_summary.csv` — map-level mean/min/max correction summary.
"""
    (out_dir / "README.md").write_text(report)
    raster_summary.to_csv(out_dir / "raster_summary.csv", index=False)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create trained-vs-untrained model6 soil-moisture map comparisons.")
    parser.add_argument("--model6-dense-dir", type=Path, default=DEFAULT_MODEL6_DENSE_DIR)
    parser.add_argument("--validation-dir", type=Path, default=DEFAULT_VALIDATION_DIR)
    parser.add_argument("--method", choices=["knn", "ridge"], default="knn")
    parser.add_argument("--knn-neighbors", type=int, default=12)
    parser.add_argument("--clip-min", type=float, default=0.0)
    parser.add_argument("--clip-max", type=float, default=60.0)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    generate_maps(args)
    print(f"wrote {args.model6_dense_dir / 'SM_comparison'}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
