"""Retrain model6-style HGBR on the dense point dataset with larger leaves.

This is a local-device retrain: it uses the dense point/date feature table
generated by ``dense_validation_and_spiking.py`` and fits the model6 feature set
directly to the dense observations.

It is intentionally separate from the shipped OzNet model6 artifact. The output
is a local model and map set for this dense site/device.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from soilmoisture_points_validation.make_sm_comparison_maps import (  # noqa: E402
    DEFAULT_MODEL6_DENSE_DIR,
    DEFAULT_VALIDATION_DIR,
    NODATA,
    _open_template,
    _rasterio,
    _write_multiband,
    _write_single_band,
    bbox_from_predictions,
    build_dynamic_layers,
    build_static_layers,
    grid_dataframe,
    make_figure,
    query_stub,
)


def parse_leaf(value: str):
    return None if value.lower() in {"none", "unlimited", "null"} else int(value)


def estimator(max_leaf_nodes, min_samples_leaf, max_iter, max_features):
    from sklearn.ensemble import HistGradientBoostingRegressor

    return HistGradientBoostingRegressor(
        learning_rate=0.03,
        max_iter=max_iter,
        max_leaf_nodes=max_leaf_nodes,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        l2_regularization=1.0,
        random_state=0,
        early_stopping=False,
    )


def metrics(y_true, y_pred) -> dict:
    from emt.evaluation import metrics as _metrics

    return _metrics(y_true, y_pred)


def load_feature_rows(model6_dense_dir: Path, features: list[str]) -> pd.DataFrame:
    p = model6_dense_dir / "stage1_dense_unseen_validation" / "point_date_model_inputs.csv"
    df = pd.read_csv(p).replace([np.inf, -np.inf], np.nan)
    required = features + ["obs_sm_pct", "pred_sm_pct", "point", "date", "lon", "lat"]
    return df.dropna(subset=required).reset_index(drop=True)


def leaf_sweep(
    df: pd.DataFrame,
    features: list[str],
    leaf_options: list,
    min_leaf_options: list[int],
    max_iter: int,
    max_features: float,
    n_splits: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    from sklearn.model_selection import GroupKFold

    X = df[features]
    y = df["obs_sm_pct"]
    groups = df["point"]
    cv = GroupKFold(n_splits=n_splits)

    rows = []
    pred_frames = []
    for leaves in leaf_options:
        for min_leaf in min_leaf_options:
            preds = np.full(len(df), np.nan, dtype=float)
            for train_idx, test_idx in cv.split(X, y, groups):
                est = estimator(leaves, min_leaf, max_iter=max_iter, max_features=max_features)
                est.fit(X.iloc[train_idx], y.iloc[train_idx])
                preds[test_idx] = est.predict(X.iloc[test_idx])
            m = metrics(y, preds)
            record = {
                "max_leaf_nodes": "None" if leaves is None else int(leaves),
                "min_samples_leaf": int(min_leaf),
                "max_iter": int(max_iter),
                "max_features": float(max_features),
                **m,
            }
            rows.append(record)
            pred_frames.append(
                df[["point", "date", "obs_sm_pct", "pred_sm_pct"]].assign(
                    cv_pred=preds,
                    max_leaf_nodes=record["max_leaf_nodes"],
                    min_samples_leaf=min_leaf,
                )
            )
            print(record, flush=True)
    sweep = pd.DataFrame(rows).sort_values("nse", ascending=False).reset_index(drop=True)
    preds = pd.concat(pred_frames, ignore_index=True)
    return sweep, preds


def fit_final(df: pd.DataFrame, features: list[str], leaves, min_leaf: int, max_iter: int, max_features: float):
    est = estimator(leaves, min_leaf, max_iter=max_iter, max_features=max_features)
    est.fit(df[features], df["obs_sm_pct"])
    in_sample = est.predict(df[features])
    return est, metrics(df["obs_sm_pct"], in_sample), in_sample


def output_dirs(model6_dense_dir: Path, label: str) -> dict[str, Path]:
    root = model6_dense_dir / "SM_comparison" / label
    dirs = {
        "root": root,
        "untrained": root / "untrained_model6",
        "trained": root / "trained_model6_more_leaves",
        "delta": root / "trained_minus_untrained",
        "multiband": root / "multiband",
        "figures": root / "figures",
    }
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)
    return dirs


def generate_retrained_maps(
    df: pd.DataFrame,
    model,
    features: list[str],
    model6_dense_dir: Path,
    validation_dir: Path,
    dirs: dict[str, Path],
    clip_min: float,
    clip_max: float,
) -> pd.DataFrame:
    from PaddockTS.query import Query

    dates = sorted(df["date"].unique())
    bbox = bbox_from_predictions(df)
    template = _open_template(validation_dir / "tifs" / f"soil_moisture_{dates[0]}.tif")
    q = Query(
        bbox=list(bbox),
        start=pd.Timestamp(dates[0]).date(),
        end=pd.Timestamp(dates[-1]).date(),
        stub=query_stub(bbox, dates[0], dates[-1]),
    )
    static_layers = build_static_layers(q, template)
    dynamic_by_day = build_dynamic_layers(q, dates, bbox, template)

    rows = []
    for i, day in enumerate(dates, 1):
        print(f"writing retrained model6 maps {i}/{len(dates)}: {day}", flush=True)
        src_tif = validation_dir / "tifs" / f"soil_moisture_{day}.tif"
        with _rasterio().open(src_tif) as src:
            profile = src.profile.copy()
            untrained = src.read(1).astype("float32")
            if src.nodata is not None:
                untrained = np.where(untrained == src.nodata, np.nan, untrained)

        X = grid_dataframe(features, static_layers, dynamic_by_day[day], untrained)
        X = X[features].replace([np.inf, -np.inf], np.nan)
        valid = np.isfinite(untrained.ravel()) & np.isfinite(X).all(axis=1).to_numpy()
        trained = np.full(untrained.size, np.nan, dtype="float32")
        if valid.any():
            trained[valid] = model.predict(X.loc[valid, features]).astype("float32")
        trained = trained.reshape(untrained.shape)
        trained = np.clip(trained, clip_min, clip_max)
        delta = trained - untrained

        shutil.copy2(src_tif, dirs["untrained"] / f"untrained_model6_{day}.tif")
        _write_single_band(dirs["trained"] / f"trained_model6_more_leaves_{day}.tif", trained, profile, "trained_model6_more_leaves_sm_pct")
        _write_single_band(dirs["delta"] / f"trained_minus_untrained_{day}.tif", delta, profile, "trained_minus_untrained_sm_pct")
        _write_multiband(
            dirs["multiband"] / f"SM_comparison_model6_more_leaves_{day}.tif",
            [untrained, trained, delta],
            profile,
            ["untrained_model6_sm_pct", "trained_model6_more_leaves_sm_pct", "trained_minus_untrained_sm_pct"],
        )
        make_figure(day, untrained, trained, delta, dirs["figures"] / f"SM_comparison_model6_more_leaves_{day}.png")
        rows.append(
            {
                "date": day,
                "untrained_mean": float(np.nanmean(untrained)),
                "trained_mean": float(np.nanmean(trained)),
                "delta_mean": float(np.nanmean(delta)),
                "delta_min": float(np.nanmin(delta)),
                "delta_max": float(np.nanmax(delta)),
                "valid_pixels": int(np.isfinite(trained).sum()),
            }
        )
    out = pd.DataFrame(rows)
    out.to_csv(dirs["root"] / "raster_summary.csv", index=False)
    return out


def fmt(value, digits=3) -> str:
    return "NA" if value is None or not np.isfinite(float(value)) else f"{float(value):.{digits}f}"


def write_report(
    dirs: dict[str, Path],
    sweep: pd.DataFrame,
    final_metrics: dict,
    untrained_metrics: dict,
    params: dict,
    raster_summary: pd.DataFrame,
) -> None:
    best = sweep.head(12).copy()
    delta = {
        "nse": final_metrics["nse"] - untrained_metrics["nse"],
        "rmse": final_metrics["rmse"] - untrained_metrics["rmse"],
        "bias": final_metrics["bias"] - untrained_metrics["bias"],
        "r": final_metrics["r"] - untrained_metrics["r"],
    }

    def markdown_table(df: pd.DataFrame) -> str:
        cols = list(df.columns)
        lines = [
            "| " + " | ".join(cols) + " |",
            "| " + " | ".join(["---"] * len(cols)) + " |",
        ]
        for _, row in df.iterrows():
            vals = []
            for col in cols:
                val = row[col]
                vals.append(f"{val:.3f}" if isinstance(val, (float, np.floating)) else str(val))
            lines.append("| " + " | ".join(vals) + " |")
        return "\n".join(lines)

    report = f"""# Dense-site model6 retrain with more leaves

This folder contains a local retrain of model6-style `HistGradientBoostingRegressor`
on the dense point dataset.

## Selected local model

| parameter | value |
|---|---:|
| max_leaf_nodes | {params["max_leaf_nodes"]} |
| min_samples_leaf | {params["min_samples_leaf"]} |
| max_iter | {params["max_iter"]} |
| max_features | {params["max_features"]} |

The leaf sweep found that 127, 255, 511 and unlimited leaves produce effectively
the same held-out score at a fixed `min_samples_leaf`. For this dense device
dataset, the practical limit is sample support per leaf rather than the explicit
leaf cap. I therefore used 511 leaves with `min_samples_leaf=20`: more expressive
than the shipped cap, but still supported by the local sample size.

## Point-level performance

| metric | shipped/untrained model6 | local model6 more-leaves fit | delta |
|---|---:|---:|---:|
| NSE / R² | {fmt(untrained_metrics["nse"])} | {fmt(final_metrics["nse"])} | {fmt(delta["nse"])} |
| Pearson r | {fmt(untrained_metrics["r"])} | {fmt(final_metrics["r"])} | {fmt(delta["r"])} |
| RMSE | {fmt(untrained_metrics["rmse"])} | {fmt(final_metrics["rmse"])} | {fmt(delta["rmse"])} |
| bias | {fmt(untrained_metrics["bias"])} | {fmt(final_metrics["bias"])} | {fmt(delta["bias"])} |

The final-fit metrics are in-sample. Use the leaf-sweep GroupKFold results below
for a less optimistic held-out estimate.

## Best GroupKFold leaf-sweep settings

{markdown_table(best[["max_leaf_nodes", "min_samples_leaf", "rmse", "ubrmse", "bias", "r", "nse", "n"]])}

## Outputs

- `model6_more_leaves_dense_points.joblib` — fitted local model.
- `leaf_sweep_groupkfold.csv` — point-group held-out leaf sweep.
- `leaf_sweep_predictions.csv` — out-of-fold predictions for all sweep settings.
- `point_predictions_model6_more_leaves.csv` — point-level shipped vs local predictions.
- `trained_model6_more_leaves/` — direct local retrained prediction GeoTIFFs.
- `trained_minus_untrained/` — local retrain minus shipped model6 GeoTIFFs.
- `multiband/` — three-band GeoTIFFs: shipped model6, retrained model6, difference.
- `figures/` — quick-look PNG triptychs.
- `raster_summary.csv` — map-level mean/min/max differences.

## Caveat

This is a local dense-site retrain against the dense point observations. It is
not a replacement for the national OzNet-trained model unless its transfer skill
is separately validated outside this site.
"""
    (dirs["root"] / "README.md").write_text(report)


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Retrain model6 locally on dense point data with a larger leaf budget.")
    parser.add_argument("--model6-dense-dir", type=Path, default=DEFAULT_MODEL6_DENSE_DIR)
    parser.add_argument("--validation-dir", type=Path, default=DEFAULT_VALIDATION_DIR)
    parser.add_argument("--max-leaf-nodes", type=parse_leaf, default=511)
    parser.add_argument("--min-samples-leaf", type=int, default=20)
    parser.add_argument("--max-iter", type=int, default=300)
    parser.add_argument("--max-features", type=float, default=0.3)
    parser.add_argument("--leaf-options", nargs="+", default=["127", "255", "511", "None"])
    parser.add_argument("--min-leaf-options", nargs="+", type=int, default=[5, 10, 20])
    parser.add_argument("--n-splits", type=int, default=5)
    parser.add_argument("--clip-min", type=float, default=0.0)
    parser.add_argument("--clip-max", type=float, default=60.0)
    return parser.parse_args(argv)


def main(argv=None) -> int:
    from emt.model6 import model as model6

    args = parse_args(argv)
    label = "model6_more_leaves_dense_points"
    dirs = output_dirs(args.model6_dense_dir, label)
    df = load_feature_rows(args.model6_dense_dir, list(model6.FEATURES))

    leaf_options = [parse_leaf(str(v)) for v in args.leaf_options]
    sweep, sweep_preds = leaf_sweep(
        df,
        list(model6.FEATURES),
        leaf_options=leaf_options,
        min_leaf_options=args.min_leaf_options,
        max_iter=args.max_iter,
        max_features=args.max_features,
        n_splits=args.n_splits,
    )
    sweep.to_csv(dirs["root"] / "leaf_sweep_groupkfold.csv", index=False)
    sweep_preds.to_csv(dirs["root"] / "leaf_sweep_predictions.csv", index=False)

    final_model, final_metrics, final_pred = fit_final(
        df,
        list(model6.FEATURES),
        leaves=args.max_leaf_nodes,
        min_leaf=args.min_samples_leaf,
        max_iter=args.max_iter,
        max_features=args.max_features,
    )
    joblib.dump(final_model, dirs["root"] / "model6_more_leaves_dense_points.joblib")
    untrained_metrics = metrics(df["obs_sm_pct"], df["pred_sm_pct"])
    point_pred = df[["point", "date", "obs_sm_pct", "pred_sm_pct"]].copy()
    point_pred["model6_more_leaves_pred"] = final_pred
    point_pred.to_csv(dirs["root"] / "point_predictions_model6_more_leaves.csv", index=False)
    with (dirs["root"] / "point_metrics_model6_more_leaves.json").open("w") as f:
        json.dump({"untrained_model6": untrained_metrics, "model6_more_leaves_in_sample": final_metrics}, f, indent=2)

    raster_summary = generate_retrained_maps(
        df,
        final_model,
        list(model6.FEATURES),
        args.model6_dense_dir,
        args.validation_dir,
        dirs,
        clip_min=args.clip_min,
        clip_max=args.clip_max,
    )
    params = {
        "max_leaf_nodes": "None" if args.max_leaf_nodes is None else args.max_leaf_nodes,
        "min_samples_leaf": args.min_samples_leaf,
        "max_iter": args.max_iter,
        "max_features": args.max_features,
    }
    write_report(dirs, sweep, final_metrics, untrained_metrics, params, raster_summary)
    print(f"wrote {dirs['root']}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
